version: '3.4'

x-env: &env
  POSTGRES_URL: database
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

services:
  cards:
    build: 
      context: ./services/cards
    environment: *env
    depends_on:
      - database

  database:
    image: postgres:16.0
    environment: *env
    volumes:
      - ./config/postgres/init-db.sh:/docker-entrypoint-initdb.d/init.sql
